// <auto-generated />
using System;
using LazyTest.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LazyTest.Migrations
{
    [DbContext(typeof(LazyTestContext))]
    [Migration("20240903134136_Change_Status_code")]
    partial class Change_Status_code
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.7");

            modelBuilder.Entity("LazyTest.Models.TestUrl", b =>
                {
                    b.Property<int>("TestUrlId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long?>("ContentLength")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DomCount")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("HttpStatusCode")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Responsetime")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StatusCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("WebsiteId")
                        .HasColumnType("INTEGER");

                    b.HasKey("TestUrlId");

                    b.HasIndex("WebsiteId");

                    b.ToTable("TestResult");
                });

            modelBuilder.Entity("LazyTest.Models.WebSite", b =>
                {
                    b.Property<int>("WebsiteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("SitemapUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("WebsiteId");

                    b.ToTable("TestSite");
                });

            modelBuilder.Entity("LazyTest.Models.TestUrl", b =>
                {
                    b.HasOne("LazyTest.Models.WebSite", "Site")
                        .WithMany("TestUrls")
                        .HasForeignKey("WebsiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Site");
                });

            modelBuilder.Entity("LazyTest.Models.WebSite", b =>
                {
                    b.Navigation("TestUrls");
                });
#pragma warning restore 612, 618
        }
    }
}
